### ISSUE TITLE
How will UI/UX be made?

### ISSUE THREAD

**Issue by DoublePlusGood23** [Quantum-Code/derby-manager#4]
As far as I can tell the UI is designed by using HTML and CSS so it should be pretty simple to make a good UI.

**Comment by azharichenko** [comment]
With a combination of AngularJS and mdl we should have a pretty good looking UI interface

**Comment by azharichenko** [comment]
I just added angular and angular materials to the project. When you clone the repository go into the directory and run `npm start` this shall get `npm` and `bower` to grab and install all the components of node and angular.
